import { afterAll,describe,expect,it } from 'vitest';
import { db } from '../../packages/db/src/index';
import { AIProviderError,FakeExtractionProvider } from '../../packages/ai/src/index';
import { ExtractionService } from '../../apps/api/src/services/extraction';
const raw=process.env.TEST_DATABASE_URL;if(!raw||raw!==process.env.DATABASE_URL||process.env.NODE_ENV==='production'||!new URL(raw).pathname.includes('suppliesignal_test_'))throw new Error('Refusing non-disposable extraction database');
afterAll(async()=>db.$disconnect());
async function fixture(){const source=await db.source.create({data:{name:'SupplySignal Test Fixture',sourceType:'MANUAL',baseUrl:'https://fixture.example',category:'OTHER',reliability:'LOW',active:true,collectionEnabled:false}});const article=await db.sourceArticle.create({data:{sourceId:source.id,originalUrl:'https://fixture.example/fictional',canonicalUrl:'https://fixture.example/fictional',title:'Fictional test article — not real-world intelligence',normalizedText:'Workers began a strike at the fictional North Test Factory in Gazipur.',contentHash:crypto.randomUUID(),urlHash:crypto.randomUUID(),status:'NORMALIZED'}});return{source,article};}
const output={articleRelevant:true,claims:[{claimType:'STRIKE',assertionMode:'OBSERVED',statement:'Workers began a strike at the fictional factory.',confidence:0.93,evidenceText:'Workers began a strike at the fictional North Test Factory in Gazipur.',entities:[{entityType:'FACTORY',name:'North Test Factory',role:'affected',confidence:0.9}],locations:[{name:'Gazipur',city:'Gazipur',country:'Bangladesh',confidence:0.98}]}]};
describe.sequential('Phase 4 extraction with PostgreSQL',()=>{
 it('preserves successful history, determines latest success, and survives failed reprocessing',async()=>{const{article}=await fixture();const service=new ExtractionService(new FakeExtractionProvider(output));const first=await service.extract(article.id);const firstClaimId=first.claims[0]!.id;const second=await service.extract(article.id);expect(second.id).toBe(first.id);const reprocessed=await service.extract(article.id,true);expect(reprocessed.id).not.toBe(first.id);const failing=new ExtractionService(new FakeExtractionProvider({articleRelevant:true,claims:[{...output.claims[0],evidenceText:'Invented evidence'}]}));await expect(failing.extract(article.id,true)).rejects.toMatchObject({code:'INVALID_EVIDENCE'});const history=await service.articleRuns(article.id);expect(history).toHaveLength(3);expect(history.find((run)=>run.id===first.id)?.claims[0]?.id).toBe(firstClaimId);expect(history.find((run)=>run.id===reprocessed.id)?.status).toBe('COMPLETED');expect(history[0]?.status).toBe('FAILED');const latestSuccessful=history.find((run)=>run.status==='COMPLETED');expect(latestSuccessful?.id).toBe(reprocessed.id);expect(await db.claim.findUnique({where:{id:firstClaimId}})).not.toBeNull();const claim=await service.getClaim(reprocessed.claims[0]!.id);expect(claim).toMatchObject({sourceArticle:{originalUrl:'https://fixture.example/fictional'},entities:[{name:'North Test Factory'}],locations:[{name:'Gazipur'}]});});
 it('persists safe failure and no claims for invalid evidence',async()=>{const{article}=await fixture();const service=new ExtractionService(new FakeExtractionProvider({articleRelevant:true,claims:[{...output.claims[0],evidenceText:'Invented evidence'}]}));await expect(service.extract(article.id)).rejects.toMatchObject({code:'INVALID_EVIDENCE'});expect(await db.claim.count({where:{sourceArticleId:article.id}})).toBe(0);expect(await db.articleExtractionRun.findFirst({where:{sourceArticleId:article.id}})).toMatchObject({status:'FAILED',errorCode:'INVALID_EVIDENCE'});});
 it('bounds transient retries and does not retry permanent errors',async()=>{const{article}=await fixture();let transient=0;const transientProvider={name:'fake',model:'retry',extract:async()=>{transient++;throw new AIProviderError('AI_TIMEOUT','timeout',true);}};await expect(new ExtractionService(transientProvider).extract(article.id)).rejects.toMatchObject({code:'AI_TIMEOUT'});expect(transient).toBe(3);let permanent=0;const permanentProvider={name:'fake',model:'permanent',extract:async()=>{permanent++;throw new AIProviderError('AI_PROVIDER_ERROR','bad',false);}};await expect(new ExtractionService(permanentProvider).extract(article.id,true)).rejects.toMatchObject({code:'AI_PROVIDER_ERROR'});expect(permanent).toBe(1);});
 it('rejects empty content and atomically leases across service instances',async()=>{const{source}=await fixture();const empty=await db.sourceArticle.create({data:{sourceId:source.id,originalUrl:'https://fixture.example/empty',title:'Empty',contentHash:crypto.randomUUID(),urlHash:crypto.randomUUID(),status:'COLLECTED'}});await expect(new ExtractionService(new FakeExtractionProvider(output)).extract(empty.id)).rejects.toMatchObject({code:'ARTICLE_NOT_ELIGIBLE'});let release!:(value:{output:typeof output})=>void;const pending=new Promise<{output:typeof output}>((resolve)=>{release=resolve;});let providerCalls=0;const provider={name:'fake',model:'slow',extract:()=>{providerCalls++;return pending;}};const{article}=await fixture();const serviceA=new ExtractionService(provider);const serviceB=new ExtractionService(provider);const first=serviceA.extract(article.id);await new Promise((resolve)=>setTimeout(resolve,20));await expect(serviceB.extract(article.id)).rejects.toMatchObject({code:'EXTRACTION_ALREADY_RUNNING'});expect(providerCalls).toBe(1);expect(await db.articleExtractionRun.count({where:{sourceArticleId:article.id,status:'PROCESSING'}})).toBe(1);release({output});await expect(first).resolves.toMatchObject({status:'COMPLETED'});expect(await db.articleExtractionLease.count({where:{sourceArticleId:article.id}})).toBe(0);});
 it('recovers an expired database lease and closes its abandoned run',async()=>{const{article}=await fixture();await db.articleExtractionLease.create({data:{sourceArticleId:article.id,ownerToken:crypto.randomUUID(),leaseExpiresAt:new Date(Date.now()-1000)}});const abandoned=await db.articleExtractionRun.create({data:{sourceArticleId:article.id,provider:'fake',model:'crashed',promptVersion:'1.0',schemaVersion:'1.0',inputHash:'pending',inputCharacters:10}});await expect(new ExtractionService(new FakeExtractionProvider(output)).extract(article.id,true)).resolves.toMatchObject({status:'COMPLETED'});expect(await db.articleExtractionRun.findUnique({where:{id:abandoned.id}})).toMatchObject({status:'FAILED',errorCode:'EXTRACTION_LEASE_EXPIRED'});});
});
