CREATE TYPE "ClaimSignal" AS ENUM ('AFFIRMS_EVENT','DENIES_EVENT','RESOLUTION_SIGNAL','CANCELLATION_SIGNAL','NEUTRAL');

ALTER TABLE "events"
  ADD COLUMN "policy_version" TEXT NOT NULL DEFAULT '1.0';

ALTER TABLE "events"
  ALTER COLUMN "policy_version" SET DEFAULT '1.1';

ALTER TABLE "event_claims"
  ADD COLUMN "claim_signal" "ClaimSignal" NOT NULL DEFAULT 'AFFIRMS_EVENT';
