import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiRequest } from '../lib/api';
import { useWorkspace } from '../lib/workspace';

type Exposure = { id: string; status: string; primaryExposureType: string; matchConfidence: string; firstDetectedAt: string; event: { title: string; severity: string; summary: string; claimLinks?: Array<{ claim: { id: string; statement: string; evidenceText: string; sourceArticle: { title: string; originalUrl: string; source: { name: string } } } }> }; paths: Array<{ id: string; reasonCodes: string[]; steps: Array<{ id: string; sequence: number; nodeType: string; labelSnapshot: string; edgeFromPrevious?: string | null }> }> };
type Candidate = { id: string; status: string; reasonCodes: string[]; confidence?: string | null; event: { title: string }; nodes: Array<{ id: string; nodeType: string; snapshot: { name?: string; label?: string } }> };
type Identity = { id: string; subjectType: string; namespace: string; identifier: string; verificationStatus: string };
const reason = { reasonCode: 'AMBIGUOUS_ENTITY_IDENTITY' };

function Page({ title, children }: { title: string; children: React.ReactNode }) { return <section className="p-5 sm:p-8"><h1 className="mb-5 text-2xl font-semibold">{title}</h1>{children}</section>; }
export function ExposuresPage() {
  const { customerId, user } = useWorkspace(); const [items, setItems] = useState<Exposure[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); void apiRequest<Exposure[]>(`/customers/${customerId}/exposures`).then(setItems).catch(() => setError('Customer exposures could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(load, [customerId]);
  const review = async (id: string, action: 'confirm' | 'dismiss') => { await apiRequest(`/customers/${customerId}/exposures/${id}/${action}`, { method: 'POST', body: JSON.stringify(reason) }); load(); };
  return <Page title="Customer exposures"><p className="mb-5 text-sm text-muted">Deterministic Event-to-graph findings. Confidence describes match certainty, not risk.</p>{loading && <p className="text-sm text-muted">Loading exposures…</p>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{!loading && !error && items.length === 0 && <p className="text-sm text-muted">No customer exposures found.</p>}<div className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border bg-white p-4"><Link className="font-semibold text-signal" to={`/exposures/${item.id}`}>{item.event.title}</Link><p className="text-sm">{item.event.severity} · {item.primaryExposureType} · {item.status} · confidence {item.matchConfidence}</p><p className="text-sm text-muted">{item.paths[0]?.steps.at(-1)?.labelSnapshot ?? 'Graph path retained'}</p>{user.role !== 'CUSTOMER' && <div className="mt-3 flex gap-2"><button className="rounded bg-emerald-700 px-3 py-1 text-white" onClick={() => void review(item.id, 'confirm')}>Confirm</button><button className="rounded border px-3 py-1" onClick={() => void review(item.id, 'dismiss')}>Dismiss</button></div>}</article>)}</div></Page>;
}
export function ExposureDetailPage() {
  const { id = '' } = useParams(); const { customerId } = useWorkspace(); const [item, setItem] = useState<Exposure | null>(null); const [error, setError] = useState('');
  useEffect(() => { setItem(null); setError(''); void apiRequest<Exposure>(`/customers/${customerId}/exposures/${id}`).then(setItem).catch(() => setError('Exposure detail could not be loaded.')); }, [customerId, id]);
  return <Page title={item?.event.title ?? 'Exposure detail'}>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{!item && !error && <p className="text-sm text-muted">Loading exposure…</p>}{item && <><section className="mb-5 rounded-xl border bg-white p-5"><h2 className="font-semibold">What happened?</h2><p className="mt-2 text-sm">{item.event.summary}</p>{item.event.claimLinks?.map(({ claim }) => <div className="mt-4 border-t pt-3" key={claim.id}><p className="text-sm font-medium">{claim.statement}</p><blockquote className="mt-1 border-l-2 pl-3 text-sm text-muted">{claim.evidenceText}</blockquote><a className="text-sm text-signal" href={claim.sourceArticle.originalUrl} target="_blank" rel="noreferrer">{claim.sourceArticle.source.name}: {claim.sourceArticle.title}</a></div>)}</section><section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Why does it matter?</h2>{item.paths.map((path) => <div className="mt-3" key={path.id}><p className="text-xs text-muted">{path.reasonCodes.join(', ')}</p><ol className="mt-2 space-y-2">{path.steps.map((step) => <li key={step.id} className="rounded bg-canvas p-2 text-sm">{step.sequence + 1}. {step.nodeType}: {step.labelSnapshot}{step.edgeFromPrevious ? ` — ${step.edgeFromPrevious}` : ''}</li>)}</ol></div>)}</section></>}</Page>;
}
export function ExposureCandidatesPage() {
  const { customerId } = useWorkspace(); const [items, setItems] = useState<Candidate[]>([]); const [identities, setIdentities] = useState<Identity[]>([]); const [selected, setSelected] = useState<Record<string, string>>({}); const [error, setError] = useState('');
  const load = () => { setError(''); void Promise.all([apiRequest<Candidate[]>(`/customers/${customerId}/exposure-candidates`), apiRequest<Identity[]>(`/customers/${customerId}/graph-identities`)]).then(([a, b]) => { setItems(a); setIdentities(b.filter((value) => value.verificationStatus === 'VERIFIED')); }).catch(() => setError('Exposure candidates could not be loaded.')); }; useEffect(load, [customerId]);
  const act = async (id: string, action: 'confirm' | 'reject') => { await apiRequest(`/customers/${customerId}/exposure-candidates/${id}/${action}`, { method: 'POST', body: JSON.stringify({ ...reason, ...(action === 'confirm' ? { resultingIdentityId: selected[id] } : {}) }) }); load(); };
  return <Page title="Exposure candidate review"><p className="mb-5 text-sm text-muted">Ambiguous findings are reviewer-only and never become exposures silently.</p>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{!error && items.length === 0 && <p className="text-sm text-muted">No ambiguous candidates require review.</p>}{items.map((item) => <article className="mb-3 rounded-xl border bg-white p-4" key={item.id}><b>{item.event.title}</b><p className="text-sm">{item.status} · {item.reasonCodes.join(', ')}</p><select className="mt-3 rounded border p-2" value={selected[item.id] ?? ''} onChange={(e) => setSelected({ ...selected, [item.id]: e.target.value })}><option value="">Choose verified customer identity</option>{identities.map((identity) => <option value={identity.id} key={identity.id}>{identity.subjectType} · {identity.namespace}:{identity.identifier}</option>)}</select><div className="mt-3 flex gap-2"><button disabled={!selected[item.id]} className="rounded bg-emerald-700 px-3 py-1 text-white disabled:opacity-40" onClick={() => void act(item.id, 'confirm')}>Confirm</button><button className="rounded border px-3 py-1" onClick={() => void act(item.id, 'reject')}>Reject</button></div></article>)}</Page>;
}
export function IdentityReviewPage() {
  const { customerId, user } = useWorkspace(); const [items, setItems] = useState<Identity[]>([]); const [global, setGlobal] = useState<Array<Identity & { eventEntity: { name: string; event: { title: string } } }>>([]); const [error, setError] = useState('');
  const load = () => { setError(''); void apiRequest<Identity[]>(`/customers/${customerId}/graph-identities`).then(setItems).catch(() => setError('Customer identities could not be loaded.')); if (user.role === 'ADMIN') void apiRequest<typeof global>('/admin/event-identifiers').then(setGlobal).catch(() => setError('Global identity proposals could not be loaded.')); }; useEffect(load, [customerId, user.role]);
  const setStatus = async (id: string, action: 'verify' | 'reject', globalIdentity = false) => { await apiRequest(`${globalIdentity ? '/admin/event-identifiers' : `/customers/${customerId}/graph-identities`}/${id}/${action}`, { method: 'POST' }); load(); };
  return <Page title="Identity review">{error && <p role="alert" className="mb-3 text-sm text-red-700">{error}</p>}<h2 className="mb-2 font-semibold">Customer graph identities</h2>{items.length === 0 && !error && <p className="text-sm text-muted">No customer identities found.</p>}{items.map((item) => <div className="mb-2 rounded border bg-white p-3 text-sm" key={item.id}>{item.subjectType} · {item.namespace}:{item.identifier} · {item.verificationStatus} <button className="ml-2 text-signal" onClick={() => void setStatus(item.id, 'verify')}>Verify</button></div>)}{user.role === 'ADMIN' && <><h2 className="mb-2 mt-6 font-semibold">Global Event identity proposals</h2>{global.length === 0 && !error && <p className="text-sm text-muted">No global identity proposals found.</p>}{global.map((item) => <div className="mb-2 rounded border bg-white p-3 text-sm" key={item.id}>{item.eventEntity.event.title} · {item.eventEntity.name} · {item.namespace}:{item.identifier} · {item.verificationStatus}<button className="ml-2 text-signal" onClick={() => void setStatus(item.id, 'verify', true)}>Verify</button><button className="ml-2" onClick={() => void setStatus(item.id, 'reject', true)}>Reject</button></div>)}</>}</Page>;
}
