import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiRequest, apiDownload, ApiRequestError } from '../lib/api';
import { useWorkspace } from '../lib/workspace';

type Dataset={id:string;name:string;description?:string;status:string;provider?:string;model?:string;promptVersion?:string;schemaVersion?:string;articles?:DatasetArticle[];_count?:{articles:number;claimEvaluations:number}};
type DatasetArticle={id:string;status:string;errorCode?:string;sourceArticle:{id:string;title:string;originalUrl:string;source:{name:string}};extractionRun?:{id:string;articleRelevant:boolean|null;claims:Claim[]};evaluation?:{expectedRelevant:boolean;missedClaims:number}};
type Claim={id:string;claimType:string;statement:string;evidenceText:string;confidence:string;evaluations:{claimScore:string}[]};
type SourceArticle={id:string;title:string;source:{name:string}};
const scoreOptions=['CORRECT','PARTIALLY_CORRECT','INCORRECT','NOT_APPLICABLE'];
const errorMessage=(error:unknown)=>error instanceof ApiRequestError?`${error.code}: ${error.message}`:'Unexpected error';
const json=(method:string,body:unknown):RequestInit=>({method,body:JSON.stringify(body)});

export function PocDatasetsPage(){const{user}=useWorkspace();const[items,setItems]=useState<Dataset[]>([]);const[name,setName]=useState('');const[description,setDescription]=useState('');const[error,setError]=useState('');const load=()=>apiRequest<Dataset[]>('/poc/extraction/datasets').then(setItems).catch(e=>setError(errorMessage(e)));useEffect(()=>{void load();},[]);const create=async()=>{if(!name.trim())return;try{await apiRequest('/poc/extraction/datasets',json('POST',{name,description:description||null}));setName('');setDescription('');await load();}catch(e){setError(errorMessage(e));}};return <Page title="Extraction validation POC">{error&&<Error text={error}/>}<p className="mb-5 text-sm text-muted">Explicit, frozen evaluation datasets. Nothing is processed until an administrator starts a dataset.</p>{user.role==='ADMIN'&&<section className="mb-6 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[1fr_2fr_auto]"><input className="rounded-lg border px-3 py-2" placeholder="Dataset name" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-lg border px-3 py-2" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><button className="rounded-lg bg-ink px-4 py-2 text-white" onClick={()=>void create()}>Create dataset</button></section>}<div className="space-y-2">{items.map(item=><Link key={item.id} to={`/poc/extraction/${item.id}`} className="flex justify-between rounded-xl border bg-white p-4"><span><b>{item.name}</b><span className="block text-sm text-muted">{item.description}</span></span><span className="text-sm">{item.status} · {item._count?.articles??0} articles</span></Link>)}</div></Page>}

export function PocDatasetPage(){const{datasetId=''}=useParams();const{user}=useWorkspace();const[data,setData]=useState<Dataset|null>(null);const[available,setAvailable]=useState<SourceArticle[]>([]);const[selected,setSelected]=useState<string[]>([]);const[error,setError]=useState('');const load=()=>apiRequest<Dataset>(`/poc/extraction/datasets/${datasetId}`).then(setData).catch(e=>setError(errorMessage(e)));useEffect(()=>{void load();void Promise.all([1,2].map(page=>apiRequest<{items:SourceArticle[]}>(`/source-articles?page=${page}&pageSize=100`))).then(pages=>setAvailable(pages.flatMap(page=>page.items)));},[datasetId]);const add=async()=>{try{await apiRequest(`/poc/extraction/datasets/${datasetId}/articles`,json('POST',{articleIds:selected}));setSelected([]);await load();}catch(e){setError(errorMessage(e));}};const run=async()=>{try{const preview=await apiRequest<{total:number;compatible:number;requiringExtraction:number}>(`/poc/extraction/datasets/${datasetId}/preflight`);if(!window.confirm(`Run ${preview.total} articles? ${preview.compatible} compatible runs will be reused; ${preview.requiringExtraction} need extraction.`))return;await apiRequest(`/poc/extraction/datasets/${datasetId}/run`,{method:'POST'});await load();}catch(e){setError(errorMessage(e));}};return <Page title={data?.name??'POC dataset'}>{error&&<Error text={error}/>} {data&&<><div className="mb-5 flex flex-wrap items-center gap-3"><span className="rounded-full border bg-white px-3 py-1 text-sm">{data.status}</span>{data.provider&&<span className="text-sm text-muted">Frozen: {data.provider}/{data.model} · prompt {data.promptVersion} · schema {data.schemaVersion}</span>}<Link className="ml-auto text-signal underline" to={`/poc/extraction/${datasetId}/results`}>Results</Link></div>{user.role==='ADMIN'&&data.status==='DRAFT'&&<section className="mb-6 rounded-xl border bg-white p-4"><h2 className="font-semibold">Choose explicit articles</h2><div className="my-3 max-h-56 overflow-auto">{available.map(article=><label className="flex gap-2 border-b py-2 text-sm" key={article.id}><input type="checkbox" checked={selected.includes(article.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,article.id]:s.filter(id=>id!==article.id))}/><span>{article.title} <span className="text-muted">· {article.source.name}</span></span></label>)}</div><div className="flex gap-2"><button disabled={!selected.length} className="rounded-lg border px-4 py-2 disabled:opacity-50" onClick={()=>void add()}>Add selected</button><button disabled={!data.articles?.length} className="rounded-lg bg-ink px-4 py-2 text-white disabled:opacity-50" onClick={()=>void run()}>Preflight and run</button></div></section>}<div className="space-y-4">{data.articles?.map(article=><ArticleReview key={article.id} datasetId={datasetId} article={article} onSaved={load}/>)}</div></>}</Page>}

function ArticleReview({datasetId,article,onSaved}:{datasetId:string;article:DatasetArticle;onSaved:()=>Promise<void>|void}){const[expected,setExpected]=useState(article.evaluation?.expectedRelevant??false);const[missed,setMissed]=useState(article.evaluation?.missedClaims??0);const[error,setError]=useState('');const reviewArticle=async()=>{try{await apiRequest(`/poc/extraction/datasets/${datasetId}/articles/${article.id}/evaluation`,json('PUT',{expectedRelevant:expected,missedClaims:missed}));await onSaved();}catch(e){setError(errorMessage(e));}};return <section className="rounded-xl border bg-white p-4">{error&&<Error text={error}/>}<div className="flex justify-between"><a href={article.sourceArticle.originalUrl} target="_blank" rel="noreferrer" className="font-semibold text-signal underline">{article.sourceArticle.title}</a><span className="text-sm">{article.status}{article.errorCode?` · ${article.errorCode}`:''}</span></div><p className="text-sm text-muted">{article.sourceArticle.source.name} · extracted relevance: {String(article.extractionRun?.articleRelevant??'not available')}</p>{article.extractionRun&&<><div className="my-3 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={expected} onChange={e=>setExpected(e.target.checked)}/> expected relevant</label><label>Missed claims <input className="w-20 rounded border px-2" type="number" min="0" value={missed} onChange={e=>setMissed(Number(e.target.value))}/></label><button className="rounded border px-3" onClick={()=>void reviewArticle()}>Save article review</button></div>{article.extractionRun.claims.map(claim=><ClaimReview key={claim.id} datasetId={datasetId} claim={claim}/>)}</>}</section>}

function ClaimReview({datasetId,claim}:{datasetId:string;claim:Claim}){const[score,setScore]=useState(claim.evaluations[0]?.claimScore??'CORRECT');const[unsupported,setUnsupported]=useState(false);const[saved,setSaved]=useState(false);const save=async()=>{await apiRequest(`/poc/extraction/datasets/${datasetId}/claims/${claim.id}/evaluation`,json('PUT',{claimScore:score,evidenceScore:score,entityScore:score,locationScore:score,dateScore:score,assertionScore:score,unsupported}));setSaved(true);};return <div className="mt-3 rounded-lg bg-canvas p-3 text-sm"><b>{claim.claimType}</b><p>{claim.statement}</p><blockquote className="my-2 border-l-2 pl-3 text-muted">{claim.evidenceText}</blockquote><div className="flex flex-wrap gap-2"><select className="rounded border px-2" value={score} onChange={e=>{setScore(e.target.value);setSaved(false);}}>{scoreOptions.map(v=><option key={v}>{v}</option>)}</select><label><input type="checkbox" checked={unsupported} onChange={e=>setUnsupported(e.target.checked)}/> unsupported</label><button className="rounded border px-3" onClick={()=>void save()}>{saved?'Saved':'Save claim review'}</button></div></div>}

export function PocResultsPage(){const{datasetId=''}=useParams();const[data,setData]=useState<{decision:string;coverage:Record<string,number>;metrics:Record<string,number|null>;checks:Record<string,boolean>}|null>(null);useEffect(()=>{void apiRequest<typeof data>(`/poc/extraction/datasets/${datasetId}/results`).then(setData);},[datasetId]);return <Page title="POC results">{data&&<><div className="mb-5 rounded-xl border bg-white p-5 text-2xl font-semibold">Decision: {data.decision}</div><h2 className="mb-2 font-semibold">Coverage</h2><Cards values={data.coverage}/><h2 className="mb-2 mt-6 font-semibold">Quality metrics</h2><Cards values={data.metrics}/><div className="mt-5 flex gap-3"><button className="text-signal underline" onClick={()=>void apiDownload(`/poc/extraction/datasets/${datasetId}/export.json`,`poc-${datasetId}.json`)}>Export JSON</button><button className="text-signal underline" onClick={()=>void apiDownload(`/poc/extraction/datasets/${datasetId}/export.csv`,`poc-${datasetId}.csv`)}>Export CSV</button></div></>}</Page>}
function Cards({values}:{values:Record<string,number|null>}){return <div className="grid gap-2 sm:grid-cols-3">{Object.entries(values).map(([key,value])=><div className="rounded-lg border bg-white p-3" key={key}><span className="block text-xs text-muted">{key}</span>{value===null?'n/a':typeof value==='number'&&value<=1?`${(value*100).toFixed(1)}%`:value}</div>)}</div>}
function Page({title,children}:{title:string;children:React.ReactNode}){return <div className="p-5 sm:p-8"><h1 className="mb-6 text-2xl font-semibold">{title}</h1>{children}</div>};function Error({text}:{text:string}){return <div role="alert" className="mb-4 rounded bg-red-50 p-3 text-red-800">{text}</div>}
